---
title: "Final Project"
author: "Matthias Ronnau"
date: "May 14, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(survey)
library(VIM)
```

```{r}
data <- read_tsv("09833-0001-Data.tsv")
```

```{r}
new_data <- data.frame(Stratum = data$VESTR,
                       Replicate = data$VEREP,
                       PSU = data$ENCPSU,
                       Segment = data$ENCSEG,
                       Household = data$ENCCASE,
                       Weights = data$ANALWT,
                       PostFac = data$POSTFAC,
                       Region = factor(data$REGION, levels = 1:4, labels = c("Northeast", "North Central", "South", "West")),
                       Division = factor(data$DIVISION, levels = 1:9, labels = c("New England", "Middle Atlantic", "East North Central", "West North Central", "South Atlantic", "East South Central", "West South Central", "Mountain", "Pacific")),
                       Age = data$IRAGE,
                       Sex = factor(data$IRSEX, levels = 1:2, labels = c("Male", "Female")),
                       Race = factor(data$IRRACE, levels = 1:4, labels = c("AI/AN", "Asian/PI", "Black", "White")),
                       Hispanic = factor(data$IRHOIND, levels = 1:2, labels = c("Hispanic", "Not Hispanic")),
                       MaritalStatus = factor(data$IRMARIT, levels = c(1:4, 99), labels = c("Married", "Widowed", "Divorced or Separated", "Never Married", "Legitimate Skip")),
                       Education = data$IREDUC,
                       WorkStatus = factor(data$IRWORKST, levels = 1:11, labels = c("Full-Time", "Part-Time", "Away from work", "Unemployed looking for work", "Unemployed not looking for work", "Full-Time Homemaker Only", "In School Only", "Retired", "Disabled, not able to work", "Other, in labor force", "Other, not in labor force")),
                       Insurance = c(1, 0)[data$IRINSUR],
                       YearEarnings = factor(data$IREARN, levels = c(1:13, 99), labels = c("No personal earnings", "< $5000", "$5000 to $6999", "$7000 to $8999", "$9000 to $11999", "$12000 to $14999", "$15000 to $19999", "$20000 to $24999", "$25000 to $29999", "$30000 to $39999", "$40000 to $49999", "$50000 to $74999", "> $75000", "Legitimate Skip")),
                       FamilyIncome = factor(data$IRINC47, levels = c(1:13, 99), labels = c("No personal earnings", "< $5000", "$5000 to $6999", "$7000 to $8999", "$9000 to $11999", "$12000 to $14999", "$15000 to $19999", "$20000 to $24999", "$25000 to $29999", "$30000 to $39999", "$40000 to $49999", "$50000 to $74999", "> $75000", "Legitimate Skip")),
                       HighBP = factor(data$HIGHBP, levels = c(1:2, 96:98), labels = c("Yes", "No", "Multiple Responses", "Refused", "Blank")),
                       Asthma = factor(data$ASTHMA, levels = c(1:2, 92, 94, 98), labels = c("Yes", "No", "Illegible", "Don't Know", "Blank")),
                       Psych = factor(data$TRPSYCH, levels = c(1:2, 92, 94, 98), labels = c("Yes", "No", "Illegible", "Don't Know", "Blank")),
                       Heart = factor(data$HEART, levels = c(1:2, 94:96, 98), labels = c("Yes", "No", "Don't Know", "Bad Data", "Multiple Responses", "Blank")),
                       CigTry = data$CIGTRY,
                       CigAge = data$CIGAGE,
                       CigYears = data$CIGYRS,
                       Cigs = data$PACKS,
                       AlcTry = data$ALCTRY,
                       AlcAge = data$ALCAGE,
                       Drunk = data$DRUNKYR,
                       Xanax = data$XANAX,
                       Ritalin = data$RITALIN,
                       Morphine = data$MORPHINE,
                       MJAge = data$MJAGE,
                       MJUse = data$MJTOT,
                       MJYear = data$MJYRFREQ,
                       CocAge = data$COCAGE,
                       CocUse = data$COCTOT,
                       CocYear = data$COCYRFRQ,
                       LSD = data$LSD,
                       Ecstasy = data$ECSTASY,
                       HeroinAge = data$HERAGE,
                       HeroinUse = data$HERTOT
                       )
```

```{r}
head(new_data)
```

```{r}
age_transformer <- function(x) {
  for (i in 1:length(x)) {
    if (x[i] %in% c(185, 192, 194:198)) {
      x[i] = NA
    }
    else if (x[i] %in% c(181, 191, 193, 199)) {
      x[i] = 100
    }
  }
  return(x)
}

new_data$CigTry <- age_transformer(new_data$CigTry)
new_data$CigAge <- age_transformer(new_data$CigAge)
new_data$CigYears <- age_transformer(new_data$CigYears)
new_data$AlcTry <- age_transformer(new_data$AlcTry)
new_data$AlcAge <- age_transformer(new_data$AlcAge)

transformer <- function(x) {
  for (i in 1:length(x)) {
    if (x[i] %in% c(85, 96:98)) {
      x[i] = NA
    }
    else if (x[i] %in% c(81, 91, 99)) {
      x[i] = 100
    }
    else if (x[i] %in% c(83, 93)) {
      x[i] = 0
    }
  }
  return(x)
}

new_data$Cigs <- transformer(new_data$Cigs)
new_data$Cigs <- factor(new_data$Cigs,
                        levels = c(1:5, 100),
                        labels = c("1 to 5", "6 to 15", "16 to 25", "26 to 35", "> 35", "Never Used"),
                        exclude = NULL)
new_data$Drunk <- transformer(new_data$Drunk)
new_data$Drunk <- factor(new_data$Drunk,
                         levels = c(1:9, 0, 100),
                         labels = c("Daily", "3 to 6 Days per Week",
                                    "1 to 2 Days per Week",
                                    "Several Times a Month",
                                    "1 to 2 Times a Month",
                                    "Every Month or So",
                                    "3 to 5 Days per Year",
                                    "1 to 2 Days per Year",
                                    "Never", "Never Used",
                                    "Not in the Past Year"),
                         exclude = NULL)
```

```{r}
new_data$HighBP <- c(1, 0, NA, NA, NA)[new_data$HighBP]
new_data$Asthma <- c(1, 0, NA, NA, NA)[new_data$Asthma]
new_data$Psych <- c(1, 0, NA, NA, NA)[new_data$Psych]
new_data$Heart <- c(1, 0, NA, NA, NA)[new_data$Heart]
```

```{r}
drug_transform <- function(x) {
  for (i in 1:length(x)) {
    if (x[i] %in% c(2, 91)) {
      x[i] = 0
    }
    else if (x[i] == 98) {
      x[i] = NA
    }
  }
  return(x)
}

new_data$Xanax <- drug_transform(new_data$Xanax)
new_data$Ritalin <- drug_transform(new_data$Ritalin)
new_data$Morphine <- drug_transform(new_data$Morphine)
```

```{r}
recode_use <- function(vector){
  for(i in 1:length(vector)){
    if(vector[i] %in% c(81, 91, 181, 191)){
      vector[i] = 100
    }
    else if(vector[i] %in% c(83, 93)){
      vector[i] = 200
    }
    else if(vector[i] %in% c(85, 92, 94:98, 185, 192, 194, 195, 197, 198)){
      vector[i] = NA
    }
  }
  return(vector)
}

recode_yes_no <- function(vector){
  for(i in 1:length(vector)){
    if(vector[i] %in% c(2, 81, 91)){
      vector[i] = 0
    }
    else if(vector[i] %in% c(94, 98)){
      vector[i] = NA
    }
  }
  return(vector)
}
```

```{r}
#MJAge
new_data$MJAge = recode_use(new_data$MJAge)
head(new_data$MJAge)
```

```{r}
#MJUse
new_data$MJUse = recode_use(new_data$MJUse)
new_data$MJUse = factor(new_data$MJUse, levels = c(1:7, 100),
                        labels = c("1 or 2 Times", "3 to 5 Times", "6 to 10 Times", "11 to 49 Times", "50 to 99 Times", "100 to 199 Times", "200 or More Times", "Never"), exclude = NULL)
head(new_data$MJUse)
```

```{r}
#MJYear
new_data$MJYear <- as.factor(new_data$MJYear)
levels(new_data$MJYear) <- c("Several Times a Day", "Daily", "Almost Daily", "1 or 2 Days a Week", "Several Times a Month", "1 to 2 Times a Month", "Every Other Month", "3 to 5 Days in the Past 12 Months", "1 or 2 Days in the Past 12 Months", "Never Used", "Not in Past 12", NA, "Never Used", "Not in Past 12", NA)
```

```{r}
#CocAge
new_data$CocAge = recode_use(new_data$CocAge)
head(new_data$CocAge)
```

```{r}
#CocUse
new_data$CocUse = recode_use(new_data$CocUse)
new_data$CocUse <- factor(new_data$CocUse, levels = c(1:7, 100),
                          labels = c("1 to 2 Times", "3 to 5 Times", "6 to 10 Times", "11 to 49 Times", "50 to 99 Times", "100 to 199 Times", "200 or More Times", "Never"), exclude = NULL)
head(new_data$CocUse)
```

```{r}
#CocYear
new_data$CocYear <- as.factor(new_data$CocYear)
levels(new_data$CocYear) <- c("Daily", "Almost Daily", "1 or 2 Days a Week", "Several Times a Month", "1 to 2 Times a Month", "Every Other Month", "3 to 5 Days in the Past 12 Months", "1 or 2 Days in the Past 12 Months", "Never Used", "Not in Past 12", NA, "Never Used", "Not in Past 12", NA, NA)
```

```{r}
#LSD
new_data$LSD = recode_yes_no(new_data$LSD)
head(new_data$LSD)
```

```{r}
#Ecstacy
new_data$Ecstasy = recode_yes_no(new_data$Ecstasy)
head(new_data$Ecstasy)
```

```{r}
#HeroinAge
new_data$HeroinAge = recode_use(new_data$HeroinAge)
head(new_data$HeroinAge)
```

```{r}
#HeroinUse
new_data$HeroinUse = recode_use(new_data$HeroinUse)
new_data$HeroinUse <- factor(new_data$HeroinUse, levels = c(1:7, 100),
                             labels = c("1 or 2 Times", "3 to 5 Times", "6 to 10 Times", "11 to 49 Times", "50 to 99 Times", "100 to 199 Times", "200 or More Times", "Never"), exclude = NULL)
head(new_data$HeroinUse)
```

```{r}
head(new_data)
```

```{r}
age_create <- function(x) {
  for (i in 1:length(x)) {
    if (x[i] < 18) {
      x[i] = 1
    }
    else if (x[i] < 30) {
      x[i] = 2
    }
    else if (x[i] < 40) {
      x[i] = 3
    }
    else if (x[i] < 50) {
      x[i] = 4
    }
    else if (x[i] < 60) {
      x[i] = 5
    }
    else if (x[i] < 70) {
      x[i] = 6
    }
    else {
      x[i] = 7
    }
  }
  x = factor(x, levels = 1:7, labels = c("< 18", "19 to 29", "30 to 39", "40 to 49", "50 to 59", "60 to 69", ">= 70"))
  return(x)
}

new_data$AgeRange <- age_create(new_data$Age)

race <- function(x, y) {
  x = as.character(x)
  for (i in 1:length(x)) {
    if (y[i] == "Hispanic") {
      x[i] = "Hispanic"
    }
  }
  return(x)
}

new_data$Race <- race(new_data$Race, new_data$Hispanic)
new_data$Race <- as.factor(new_data$Race)
```

```{r}
group_education <- function(x){
  for(i in 1:length(x)){
    if(x[i] < 6){
      x[i] = 1
    }
    else if(x[i] < 9){
      x[i] = 2
      }
    else if(x[i] < 12){
     x[i]  = 3
    } 
    else if(x[i] == 12){
      x[i] = 4
    }
    else if(x[i] < 16){
      x[i] = 5
    }
    else if(x[i] == 16){
      x[i] = 6
    }
    else if(x[i] > 16){
      x[i] = 7
    }
  }
  x <- factor(x, levels = 1:7, labels = c("Some Elementary", "Some Middle", "Some High School", "High School", "Some College", "Bachelors", "Some Graduate"))
  return(x)
}

new_data$EduLevel <- group_education(new_data$Education)
```

```{r}
set.seed(251)

imputed_data <- hotdeck(new_data, variable = colnames(new_data)[20:43], ord_var = c("Region", "AgeRange", "Sex", "Race", "EduLevel", "WorkStatus", "Insurance", "FamilyIncome"))
```

```{r}
recode100 <- function(x) {
  for (i in 1:length(x)) {
    if (x[i] == 100) {
      x[i] <- NA
    }
  }
  return(x)
}

imputed_data$CigTry <- recode100(imputed_data$CigTry)
imputed_data$CigAge <- recode100(imputed_data$CigAge)
imputed_data$CigYears <- recode100(imputed_data$CigYears)
imputed_data$AlcTry <- recode100(imputed_data$AlcTry)
imputed_data$AlcAge <- recode100(imputed_data$AlcAge)
imputed_data$MJAge <- recode100(imputed_data$MJAge)
imputed_data$CocAge <- recode100(imputed_data$CocAge)
imputed_data$HeroinAge <- recode100(imputed_data$HeroinAge)
```

```{r}
design <- svydesign(ids = ~PSU + ~Household, strata = ~Division + ~Stratum + ~Segment, weights = ~Weights * ~PostFac, nest = TRUE, data = imputed_data)
options(survey.lonely.psu="adjust")
```

```{r}
svymean(~AlcAge, design = design, na.rm = TRUE)
```

```{r}
head(imputed_data, n = 50)
```

###Analysis
```{r}
Hard <- imputed_data$Morphine + as.numeric(!is.na(imputed_data$CocAge)) + as.numeric(!is.na(imputed_data$HeroinAge)) + imputed_data$LSD + imputed_data$Ecstasy
imputed_data$HardDrugs <- Hard

Opioid <- imputed_data$Morphine + as.numeric(!is.na(imputed_data$HeroinAge))
Opioid <- Opioid > 0
imputed_data$Opioid <- as.numeric(Opioid)

design <- svydesign(ids = ~PSU + ~Household, strata = ~Division + ~Stratum + ~Segment, weights = ~Weights * ~PostFac, nest = TRUE, data = imputed_data)
```

####Ritalin Usage
```{r}
ritalin_obj <- svyby(~Ritalin, design = design, FUN = svymean, by = ~AgeRange)
ritalin_obj$Ritalin <- ritalin_obj$Ritalin * 100
ritalin_obj$se <- ritalin_obj$se * 100
ritalin_obj
```

```{r}
barplot(ritalin_obj, xlab = "Age Range", ylab = "Percentage of Individuals Who Have Used Ritalin", main = "Figure 3: Barplot of Ritalin Use Between Age Groups", col = "#003262")
```

```{r}
confint(ritalin_obj)
```

####Opioid Use
```{r}
opioid_obj <- svyby(~Opioid, design = design, FUN = svymean, by = ~Division)
opioid_obj$Opioid <- opioid_obj$Opioid * 100
opioid_obj$se <- opioid_obj$se * 100
opioid_obj
```

```{r}
par(mar = c(9, 6, 5, 4))
barplot(opioid_obj, las = 2, ylab = "Percentage of Individuals \n Who Have Used Opiates", main = "Figure 4: Barplot of Opiate Usage Between Geographic Region", col = "#FDB515")
```

```{r}
confint(opioid_obj)
```


####Hard Drug Usage
```{r}
hard_marijuana_obj <- svyby(~HardDrugs, design = design, FUN = svymean, by = ~as.factor(as.numeric(!is.na(imputed_data$MJAge))))
names(hard_marijuana_obj) <- c("Marijuana", "HardDrugs", "se")
hard_marijuana_obj$HardDrugs <- hard_marijuana_obj$HardDrugs * 100
hard_marijuana_obj$se <- hard_marijuana_obj$se * 100
hard_marijuana_obj
```

```{r}
par(mar = c(6, 6, 4, 3))
barplot(hard_marijuana_obj, ylim = c(0, 100), xlab = "Marijuana Use (0 No, 1 Yes)", ylab = "Percentage of Individuals \n Who Have Used Hard Drugs", main = "Figure 5:Barplot of Hard Drug Use Between Marijuana Users", col = "#003262")
```

```{r}
confint(hard_marijuana_obj)
```

```{r}
hard_cig_obj <- svyby(~HardDrugs, design = design, FUN = svymean, by = ~as.factor(as.numeric(!is.na(imputed_data$CigAge))))
names(hard_cig_obj) <- c("Cigarettes", "HardDrugs", "se")
hard_cig_obj$HardDrugs <- hard_cig_obj$HardDrugs * 100
hard_cig_obj$se <- hard_cig_obj$se * 100
hard_cig_obj
```

```{r}
par(mar = c(6, 6, 4, 3))
barplot(hard_cig_obj, ylim = c(0, 30), xlab = "Cigarette Use (0 No, 1 Yes)", ylab = "Percentage of Individuals \n Who Have Used Hard Drugs", main = "Figure 6: Barplot of Hard Drug Use Between Cigarette Users", col = "#FDB515")
```

```{r}
confint(hard_cig_obj)
```

####Health Issues
```{r}
bp_obj <- svyby(~HighBP, FUN = svymean, design = design, by = ~as.factor(as.numeric(!is.na(imputed_data$CigAge))))
names(bp_obj) <- c("Cigarettes", "HighBP", "se")
bp_obj$HighBP <- bp_obj$HighBP * 100
bp_obj$se <- bp_obj$se * 100
bp_obj
```

```{r}
par(mar = c(6, 6, 4, 3))
barplot(bp_obj, ylim = c(0, 30), xlab = "Cigarette Use (0 No, 1 Yes)", ylab = "Percentage of Individuals \n Who Have High Blood Pressure", main = "Figure 7: Barplot of High Blood Pressure Prevalence \n Between Cigarette Users", col = "#003262")
```

```{r}
confint(bp_obj)
```

```{r}
asthma_obj <- svyby(~Asthma, FUN = svymean, design = design, by = ~as.factor(as.numeric(!is.na(imputed_data$CigAge))))
names(asthma_obj) <- c("Cigarettes", "Asthma", "se")
asthma_obj$Asthma <- asthma_obj$Asthma * 100
asthma_obj$se <- asthma_obj$se * 100
asthma_obj
```

```{r}
par(mar = c(6, 6, 4, 3))
barplot(asthma_obj, ylim = c(0, 30), xlab = "Cigarette Use (0 No, 1 Yes)", ylab = "Percentage of Individuals \n Who Have Asthma", main = "Figure 8: Barplot of Asthma Prevalence Between Cigarette Users", col = "#FDB515")
```

```{r}
confint(asthma_obj)
```

```{r}
psych_obj <- svyby(~Psych, FUN = svymean, design = design, by = ~as.factor(as.numeric(!is.na(imputed_data$CigAge))))
names(psych_obj) <- c("Cigarettes", "Psych", "se")
psych_obj$Psych <- psych_obj$Psych * 100
psych_obj$se <- psych_obj$se * 100
psych_obj
```

```{r}
par(mar = c(6, 6, 4, 3))
barplot(psych_obj, ylim = c(0, 10), xlab = "Cigarette Use (0 No, 1 Yes)", ylab = "Percentage of Individuals \n Who Have A Psychological Disorder", main = "Figure 9: Barplot of Psychological Disorder \n Prevalence Between Cigarette Users", col = "#003262")
```

```{r}
confint(psych_obj)
```

```{r}
heart_obj <- svyby(~Heart, FUN = svymean, design = design, by = ~as.factor(as.numeric(!is.na(imputed_data$CigAge))))
names(heart_obj) <- c("Cigarettes", "Heart", "se")
heart_obj$Heart <- heart_obj$Heart * 100
heart_obj$se <- heart_obj$se * 100
heart_obj
```

```{r}
par(mar = c(6, 6, 4, 3))
barplot(heart_obj, ylim = c(0, 25), xlab = "Cigarette Use (0 No, 1 Yes)", ylab = "Percentage of Individuals \n Who Have Heart Disease", main = "Figure 10: Barplot of Heart Disease Prevalence \n Between Cigarette Users", col = "#FDB515")
```

```{r}
confint(heart_obj)
```








































































